[package]
name = "trykklar-examples"
version.workspace = true
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
description.workspace = true

[dependencies]
anyhow = "1.0"
clap = { version = "4.6.6", features = ["derive"] }
trykklar = { workspace = true }
